name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 5 * * *'  # Setiap hari jam 12:00 UTC (19:00 WIB)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Query a Table on Supabase
        run: |
          # Gantilah 'your_table' dengan nama tabel nyata di Supabase
          curl -X GET "https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/maindata?limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
          
          echo "Supabase keep-alive pinged at $(date)"
