name: Supabase Keep-Alive
on:
  schedule:
    - cron: '0 0 */5 * *'  # Setiap 5 hari sekali (jam 00:00 UTC)
  workflow_dispatch:        # Memungkinkan trigger manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"